#!/usr/bin/env bash
# Write libguestfs-tools.conf using flat key=value lines (no INI sections).
set -euo pipefail

target="${1:-/etc/libguestfs-tools.conf}"
cpus="${LIBGUESTFS_CPUS:-1}"
memsize="${LIBGUESTFS_MEMSIZE:-768}"

umask 022
cat >"${target}" <<EOF
# Generated by vm-migrator — flat key=value format (no INI sections).
cpus=${cpus}
memsize=${memsize}
EOF

echo "write-libguestfs-tools-conf: wrote ${target} (cpus=${cpus}, memsize=${memsize})"
