# Generated by Django 4.2.16 on 2026-05-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0006_migration_progress_tracking'),
        ('migrations', '0011_vmwareendpointsession_datacenter_and_more'),
    ]

    operations = [
    ]
