apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmigrate
  namespace: vmigrate
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: vmigrate
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: vmigrate.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http

